/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.pricing;

import java.awt.CardLayout;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.ProductManagement.Product;
import model.Supplier.Supplier;

/**
 *
 * @author priyankasatish
 */
public class AdjustTargetPriceLowerJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Supplier supplier;

    /**
     * Creates new form AdjustTargetPriceLowerJPanel
     */
    public AdjustTargetPriceLowerJPanel(JPanel upc, Supplier supplier) {
        initComponents();
        this.userProcessContainer = upc;
        this.supplier = supplier;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductsBelowTarget = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDecrease = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(244, 237, 198));

        tblProductsBelowTarget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Below Target", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblProductsBelowTarget);

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDecrease.setBackground(new java.awt.Color(255, 204, 204));
        btnDecrease.setText("Apply Decrease");
        btnDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecreaseActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setText("ADJUST TARGET PRICE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(btnDecrease))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnBack)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecrease))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecreaseActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProductsBelowTarget.getModel();

        // Iterate through each row in the table
        for (int i = 0; i < model.getRowCount(); i++) {
            Product product = supplier.getProductCatalog().getProductList().get(i); // Find product by index
            double currentPrice = product.getTargetPrice();
            double newPrice = currentPrice * 0.90; // Reduce price by 10%

            // Round to 2 decimal places
            BigDecimal roundedPrice = new BigDecimal(newPrice).setScale(2, RoundingMode.HALF_UP);

            // Update product's target price
            product.setTargetPrice((int) roundedPrice.doubleValue());

            // Update the table with the new price
            model.setValueAt(roundedPrice.doubleValue(), i, 2);
        }
        JOptionPane.showMessageDialog(this, "Prices have been decreased by 10% for below-target products.");
    }//GEN-LAST:event_btnDecreaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDecrease;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblProductsBelowTarget;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblProductsBelowTarget.getModel();
    model.setRowCount(0); // Clear existing rows

    // Iterate through supplier's product list
    for (Product product : supplier.getProductCatalog().getProductList()) {
        int belowTargetSales = product.getNumberOfProductSalesBelowTarget();

        // Check if the product's sales are below target
        if (belowTargetSales > 0) {
            Object[] row = new Object[3];
            row[0] = product.getProductName();
            row[1] = belowTargetSales; // Number of sales below target
            row[2] = product.getTargetPrice(); // Original target price

            model.addRow(row);
        }
    }
        
    }
    
}
